[platformio]
src_dir = .
default_envs = esp_master

[env:esp_base]
platform = espressif8266
framework = arduino
board = nodemcuv2
upload_speed = 115200
build_flags =
  -Wall
  -Wextra

[env:esp_master]
extends = env:esp_base
build_src_filter =
  +<esp_master/>

[env:esp_slave]
extends = env:esp_base
build_src_filter =
  +<esp_slave/>

[env:mcu_base]
platform = intel_mcs51
board = STC89C52RC
board_build.f_cpu = 11059200L
build_flags =
  -Imcu_common
  -Wall
  -Wextra

[env:mcu_car_a]
extends = env:mcu_base
build_flags =
  ${env:mcu_base.build_flags}
  -Imcu_car_a
build_src_filter =
  +<mcu_common/>
  +<mcu_car_a/>

[env:mcu_car_b]
extends = env:mcu_base
build_flags =
  ${env:mcu_base.build_flags}
  -Imcu_car_b
build_src_filter =
  +<mcu_common/>
  +<mcu_car_b/>
